### ISSUE TITLE
Move the Readme integration tools to their own repo and publish as a library to NPM

### ISSUE THREAD

**Issue by davidmsinch** [sinch/docs#10]
The Readme integration tools in this repo (files relating to `readme.js`) are really independent from the actual content and they could be re-used by anyone who needs the same tooling.

It would make much more sense to extract it as a separate library that could just be added as a NPM dependency in to the current project.

**Comment by spacedsweden** [comment]
I like  the idea!

**Comment by davidmsinch** [comment]
This is in progress in branch https://github.com/sinch/docs/tree/refactor/extract-readmejs

After looking into the NPM repository, I had to rename the tool to `readme-sync` due to name clashes with other libraries already published on NPM.
