### ISSUE TITLE
Move away from CircleCI to GitHub Actions for publishing automation

### ISSUE THREAD

**Issue by davidmsinch** [sinch/docs#15]
GitHub actions seem to make more sense since everything related to the project would be handled within GitHub.

**Comment by spacedsweden** [comment]
can you than have actions per branch, are those public?

**Comment by davidmsinch** [comment]
Yes they are public. Workflows are defined in source files inside the Git repository. You can see an example on the `readme-sync` project: 

https://github.com/sinch/readme-sync/tree/master/.github/workflows

It's possible to trigger workflows on certain branches only, same as with CircleCI.

**Comment by davidmsinch** [comment]
This has been completed!
