### ISSUE TITLE
Send a SMS in JAVA via sinch API

### ISSUE THREAD

**Issue by mtaoufiki** [sinch/docs#25]
Hi,
I'm trying  to send a sms in java.
this is my code.
I have an account in sinch.

package sms;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import org.apache.commons.codec.binary.Base64;

public class Sms {

        		public static void main(String[] args) {
        			
        			try {
        				String phoneNumber = "myphonenumber";
        				String appKey = "mykey???";
        				String appSecret = "mysecretkey???";
        				String message = "Hello, world!";
        				
        		        URL url = new URL("https://us.sms.api.sinch.com/v1/sms/" + phoneNumber);
        		        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        		        connection.setDoOutput(true);
        		        connection.setRequestMethod("POST");
        		        connection.setRequestProperty("Content-Type", "application/json");
        		        
        		        String userCredentials = "application\\" + appKey + ":" + appSecret;
        		        byte[] encoded = Base64.encodeBase64(userCredentials.getBytes());
        		        String basicAuth = "Basic " + new String(encoded);
        		        connection.setRequestProperty("Authorization", basicAuth);
        		        
        		        String postData = "{\"Message\":\"" + message + "\"}";
        		        OutputStream os = connection.getOutputStream();
        		        os.write(postData.getBytes());
        		        
        		        StringBuilder response = new StringBuilder();
        		        BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        		        
        		        String line;
        		        while ( (line = br.readLine()) != null)
        		            response.append(line);
        		        
        		        br.close();
        		        os.close();
        		        
        		        System.out.println(response.toString());
        		
        		    } catch (IOException e) {
        		        e.printStackTrace();
        		    }
        			
        		}

        	}

thank you

**Comment by amavrb** [comment]
Hey! Sorry for the delay. 

If you've not figured it out yet, you can read more about sending messages [here].(https://developers.sinch.com/docs/sms-rest#section-send-a-batch-message). Currently you're using the wrong endpoint, the correct one is `/xms/v1/{service_plan_id}/batches`, where you can find your `service_plan_id` and API Token in the [Portal](https://dashboard.sinch.com/sms/api/rest).

The Authorization header is on the form:
`Authorization: Bearer <API TOKEN>`
Read more [here](https://developers.sinch.com/docs/sms-rest#section-authentication)

**Comment by spacedsweden** [comment]
Hi, 

The wrong tutorial is now removed. IT was a tutorial for a legacy sms api. Thanks for finding it
