### ISSUE TITLE
iOS 13 Voip problem

### ISSUE THREAD

**Issue by lum3ll** [sinch/docs#30]
Hi there,
I've been struggling in the last days for a big problem with my voip app: after updating to iOS 13 I've met all new indications from Apple about VoIP and CallKit modifications.
I've downloaded last SDK, installed everything and used your code (example app SinchCallKit), but I can't figured it out how to receive a CallKit notification when app is in background.

As for this, I've got also a problem with a specific functions you've implemented in the example code:

[self.push didCompleteProcessingPushPayload:payload];

I've got errors on this line every time I complete a build and launch a VoIP.

Anyone can help me with this problem? Thanks a lot.

**Comment by spacedsweden** [comment]
Hi

Please mail support.
