### ISSUE TITLE
SMPP Page layout feedback

### ISSUE THREAD

**Issue by BenWrightSinch** [sinch/docs#34]
I have some UI feedback. The SMPP and REST sections of SMS do not appear to match page layout. The page layout for SMPP would benefit from more closely matching the usability of the REST API layout:
https://developers.sinch.com/docs/sms-smpp

The top SMS-SMPP page does not appear to have a table of contents either.

Kind regards,
Ben

**Comment by spacedsweden** [comment]
Hi, 

you can make a pull request on the changes you want.
