### ISSUE TITLE
Please add new category called "Conversation API"

### ISSUE THREAD

**Issue by kjussakov** [sinch/docs#50]
Hi!

I'd like a new category added to the Sinch Developers Documentation site. Here are the details:

**Category name:** Conversation API
**Desired slug:** conversation-api
**Intended use:** As Conversation API closed-beta has been released we would like to give a glimpse of the new product to the wider public

Thank you!

**Comment by amavrb** [comment]
Done! :)
https://github.com/sinch/docs/tree/master/docs/conversation-api
