### ISSUE TITLE
Web to mobile apps Video calling via push notifications

### ISSUE THREAD

**Issue by shoaibHassanAttech** [sinch/docs#66]
Hi all,
i am trying to establish a video call from web to iOS/android
but receiving push with payload "loc-key = 'incoming call'"
(which does't initiate video call,i.e audio call if device is locked and crash when app is in foreground)

but when i create a call from android app to iOS device
receiving push with payload "loc-key = 'SIN_INCOMING_VIDEO_CALL'"
which successfully initiate video call on both sides.
i tried by changing template on web client same as android, but get error for invalid template error and call notification is not recieved.

**Comment by spacedsweden** [comment]
Hi, can you mail support@sinch.com about this. this repo is for docs only
